language: node_js
node_js:
- 10.9.0
cache:
  yarn: true
  directories:
        - "node_modules"
jobs:
  include:
  - stage: Test
    name: Test
    script: 
      - yarn lint
      - yarn parse
      - yarn test
  - stage: Build
    name: Build
    script: 
      - yarn build
after_success: yarn coverage
